version: '3.9'

services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=5173
    command: npm run dev
    networks:
      - routing
      - default
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.f1-api.rule=Host(`blue.devprod.fr`)'
      - 'traefik.http.routers.f1-api.entrypoints=websecure'
      - 'traefik.http.routers.f1-api.tls.certresolver=myresolver'

networks:
  routing:
    external: true
